train:
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
validation:
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
test:
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
all:
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
