train:
    ToPILImage: true
    Resize: 
      size: [{height}, {width}]
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
validation:
    ToPILImage: true
    Resize:
      size: [{height}, {width}]
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
test:
    ToPILImage: true
    Resize:
      size: [{height}, {width}]
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
all:
    ToPILImage: true
    Resize:
      size: [{height}, {width}]
    ToTensor: true
    Normalize:
      mean: [.5, .5, .5]
      std: [.5, .5, .5]
