train:
    RandomResizedCrop: 
      size: {height}
    RandomHorizontalFlip: 
      p: 0.5
    ToTensor: true
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
validation:
    Resize:
      size: {height}
    RandomAffine:
      degrees: 0
      scale: [1.143, 1.143]
      interpolation: bicubic
    CenterCrop:
      size: {height}
    ToTensor: true
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
test:
    Resize:
      size: {height}
    RandomAffine:
      degrees: 0
      scale: [1.143, 1.143]
      interpolation: bicubic
    CenterCrop:
      size: {height}
    ToTensor: true
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
all:
    Resize:
      size: {height}
    RandomAffine:
      degrees: 0
      scale: [1.143, 1.143]
      interpolation: bicubic
    CenterCrop:
      size: {height}
    ToTensor: true
    Normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
