meta:
    pod_name: vision
    script: rescale_hook
    pef: rescalenet50_tcga6k
model:
    model: rescale50
    in_height: 6144
    in_width: 6144
    drop_conv: 0.0
    drop_fc: 0.0
    num_classes: 3
task:
    task_name: msi
run: 
    batch_size: 2
    data_parallel: True
    reduce_on_rdu: True
    use_sambaloader: True
    pinned_memory: True
    use_distributed_val: True
    epochs: 1
    mode: train
    acc_test: True
    acc_thresh: 0.98
    loss_thresh: 0.03
    num_workers: 2
    run_args: "run --yaml-path"
    optim:
        learning_rate: 0.0001
        weight_decay: 0.0001 
data:
    data_dir: null
    dataset_csv_path: null
    data_transform_config: ../configs/datapipeline/tcga_rescale_data_transforms.yaml
checkpoint:
    ckpt_file: null
