meta:
    pod_name: vision
    script: rescale_hook
    pef: high_res_rescalenet50_predict
model:
    # Constants for the model
    model: rescale50
    drop_conv: 0.0
    drop_fc: 0.0
    num_classes: 1000
    in_height: 6144
    in_width: 6144
run:
    batch_size: 1
    inference: true
    enable_stoc_rounding: true
    data_parallel: false
    num_workers: 1
    pinned_memory: true
    use_sambaloader: true
    mode: eval
    run_args: "run --yaml-path"
    output: 
        log_dir: output
data:
    # Path to image data dir.
    data_dir: null
checkpoint:
    ckpt_dir: null
task: 
    task_name: csv
