meta:
    pod_name: vision
    kind: MPIJob
    num_sockets: 8
    script: rescale_hook
    pef: rescalenet50_imagenet
model:
    model: rescale50
    in_height: 224
    in_width: 224
    drop_conv: 0.03
    drop_fc: 0.3
    num_classes: 1000
task:
    task_name: "imagenet"
run:
    batch_size: 16
    data_parallel: true
    use_distributed_val: true
    epochs: 10
    reduce_on_rdu: true
    use_sambaloader: true
    pinned_memory: true
    mode: train
    enable_stoc_rounding: true
    num_workers: 7
    run_args: "run --yaml-path"
    optim:
        optimizer: sgd
        learning_rate: 0.05  # BS 128 LR
        weight_decay: 0.0001
        momentum: 0.9
        scheduler: step
    output: 
        log_dir: output

data:
    data_dir: null
    data_transform_config: ../configs/datapipeline/imagenet_data_transforms.yaml
checkpoint:
    ckpt_dir: null
