meta:
    pod_name: vision
    script: rescale_hook
    pef: rescalenet50_tcga6144_predict.pef
model:
    model: rescale50
    in_height: 6144
    in_width: 6144
    drop_conv: 0.0
    drop_fc: 0.0
    num_classes: 1000
    num_flexible_classes: 3
task: 
    task_name: msi
run: 
    batch_size: 1
    inference: true
    enable_stoc_rounding: true
    mode: eval
    acc_test: True
    acc_thresh: 0.84
    loss_thresh: 2.0
    data_parallel: false
    num_workers: 2
    run_args: "run --yaml-path" 
    pinned_memory: true
    use_sambaloader: true
    output:
        log_dir: output
data:
    data_dir: null
    data_transform_config: ../configs/datapipeline/tcga_rescale_data_transforms.yaml
checkpoint: 
    ckpt_file: null
